### ISSUE TITLE
Reg Initialization 

### ISSUE THREAD

**Issue by KoushikRaghav** [trailblazn/roboclaw#1]
var roboclaw = require("../../index").RoboClaw(0x80);

Where does this get initialize?

**Comment by trailblazn** [comment]
I see that line comes from the example scripts, not sure what you mean beyond that.

**Comment by KoushikRaghav** [comment]
Can you explain how the roboclaw object gets initialized based on the address?

**Comment by trailblazn** [comment]
I don't remember the details and I do not appear to have linked my original reference documentation, sorry about that.

However, looking at:

![image](https://user-images.githubusercontent.com/8889088/191025745-cd1404f7-49b6-4f4b-8282-7fad3cd60d19.png)

from https://github.com/trailblazn/roboclaw/blob/master/src/roboclaw_motor_controller.cc#L6-L9

The constructor appears to take the address of the device, which seems to be "0x80" by default,

It also appears to accept a baud rate.

Hope that helps!

**Comment by KoushikRaghav** [comment]
Thanks
